name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential linux-headers-$(uname -r)
    - name: make
      run: make
      working-directory: ./kernel
