name: Build and Create Release

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential linux-headers-$(uname -r)
    
    - name: Build Kernel Module
      run: make
      working-directory: ./kernel
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Images (Auto)
      if: ${{ inputs.tag_name == '' }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 --load -t hpkv-image:${{ github.ref_name }}-arm64 .
        docker save hpkv-image:${{ github.ref_name }}-arm64 | gzip > hpkv-image-arm64.tar.gz
        docker buildx build --platform linux/amd64 --load -t hpkv-image:${{ github.ref_name }}-amd64 .
        docker save hpkv-image:${{ github.ref_name }}-amd64 | gzip > hpkv-image-amd64.tar.gz

    - name: Build Docker Images (Manual)
      if: ${{ inputs.tag_name != '' }}
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 --load -t hpkv-image:${{ inputs.tag_name }}-arm64 .
        docker save hpkv-image:${{ inputs.tag_name }}-arm64 | gzip > hpkv-image-arm64.tar.gz
        docker buildx build --platform linux/amd64 --load -t hpkv-image:${{ inputs.tag_name }}-amd64 .
        docker save hpkv-image:${{ inputs.tag_name }}-amd64 | gzip > hpkv-image-amd64.tar.gz
    
    - name: Create Release (Auto)
      id: create_release_auto
      if: ${{ inputs.tag_name == '' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Create Release (Manual)
      id: create_release_manual
      if: ${{ inputs.tag_name != '' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: Release ${{ inputs.tag_name }}
        draft: false
        prerelease: false
    
    - name: Upload Kernel Module (Auto)
      if: ${{ inputs.tag_name == '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_auto.outputs.upload_url }}
        asset_path: ./kernel/hpkv_module.ko
        asset_name: hpkv_module.ko
        asset_content_type: application/octet-stream
    
    - name: Upload Kernel Module (Manual)
      if: ${{ inputs.tag_name != '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_manual.outputs.upload_url }}
        asset_path: ./kernel/hpkv_module.ko
        asset_name: hpkv_module.ko
        asset_content_type: application/octet-stream
    
    - name: Upload Docker Image ARM64 (Auto)
      if: ${{ inputs.tag_name == '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_auto.outputs.upload_url }}
        asset_path: ./hpkv-image-arm64.tar.gz
        asset_name: hpkv-image-arm64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Docker Image AMD64 (Auto)
      if: ${{ inputs.tag_name == '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_auto.outputs.upload_url }}
        asset_path: ./hpkv-image-amd64.tar.gz
        asset_name: hpkv-image-amd64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Docker Image ARM64 (Manual)
      if: ${{ inputs.tag_name != '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_manual.outputs.upload_url }}
        asset_path: ./hpkv-image-arm64.tar.gz
        asset_name: hpkv-image-arm64.tar.gz
        asset_content_type: application/gzip
    
    - name: Upload Docker Image AMD64 (Manual)
      if: ${{ inputs.tag_name != '' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_manual.outputs.upload_url }}
        asset_path: ./hpkv-image-amd64.tar.gz
        asset_name: hpkv-image-amd64.tar.gz
        asset_content_type: application/gzip

