name: Build and Create Release

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        required: false
        type: string
        description: 'Release tag (e.g., v1.0-preview)'
      kernel_version:
        required: false
        type: string
        description: 'Generic kernel version (e.g., 6.8.0-45)'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set release tag and kernel version
      run: |
        if [ -n "${{ inputs.tag_name }}" ]; then
          echo "RELEASE_TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        else
          echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        fi
        echo "KERNEL_VERSION=${{ inputs.kernel_version || '6.8.0-45' }}" >> $GITHUB_ENV

    - name: Build Docker Images
      run: |
        for arch in arm64 amd64; do
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $(pwd):/workspace -w /workspace \
            --platform linux/$arch \
            ubuntu:latest \
            /bin/bash -c "
              apt-get update && apt-get install -y docker.io
              docker buildx create --use
              docker buildx build --platform linux/$arch --file Dockerfile.$arch \
                --build-arg KERNEL_VERSION=${{ env.KERNEL_VERSION }} \
                --load -t hpkv-image:${{ env.RELEASE_TAG }}-$arch .
            "
          docker save hpkv-image:${{ env.RELEASE_TAG }}-$arch | gzip > hpkv-image-$arch.tar.gz
        done

    - name: Extract kernel modules
      run: |
        docker cp $(docker create hpkv-image:${{ env.RELEASE_TAG }}-arm64):/app/kernel/hpkv_module_arm64.ko ./kernel/
        docker cp $(docker create hpkv-image:${{ env.RELEASE_TAG }}-amd64):/app/kernel/hpkv_module_x86_64.ko ./kernel/

    - name: Print build environment details
      run: |
        for arch in amd64 arm64; do
          echo "Build environment for $arch:"
          docker run --rm hpkv-image:${{ env.RELEASE_TAG }}-$arch /bin/bash -c "
            uname -a && 
            gcc --version && 
            echo KERNEL_VERSION=\$KERNEL_VERSION &&
            modinfo /app/kernel/hpkv_module_*.ko
          "
        done

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-assets
        path: |
          ./kernel/hpkv_module_x86_64.ko
          ./kernel/hpkv_module_arm64.ko
          ./hpkv-image-amd64.tar.gz
          ./hpkv-image-arm64.tar.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

  upload_assets:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - asset_name: hpkv_module_x86_64.ko
            asset_path: kernel/hpkv_module_x86_64.ko
            content_type: application/octet-stream
          - asset_name: hpkv_module_arm64.ko
            asset_path: kernel/hpkv_module_arm64.ko
            content_type: application/octet-stream
          - asset_name: hpkv-image-amd64.tar.gz
            asset_path: hpkv-image-amd64.tar.gz
            content_type: application/gzip
          - asset_name: hpkv-image-arm64.tar.gz
            asset_path: hpkv-image-arm64.tar.gz
            content_type: application/gzip

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-assets
        path: artifacts

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.upload_url }}
        asset_path: artifacts/${{ matrix.asset_path }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: ${{ matrix.content_type }}