name: Build and Create Release

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        required: false
        type: string
        description: 'Release tag (e.g., v1.0-preview)'
      kernel_version:
        required: false
        type: string
        description: 'Generic kernel version - arm64 (e.g., 6.8.0-45)'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set release tag
      id: set_tag
      run: |
        if [ -n "${{ inputs.tag_name }}" ]; then
          echo "RELEASE_TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        else
          echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Build Docker Images
      run: |
        BUILD_ARGS=""
        if [ ! -z "${{ inputs.kernel_version }}" ]; then
          BUILD_ARGS="$BUILD_ARGS --build-arg KERNEL_VERSION=${{ inputs.kernel_version }}"
        fi
        docker buildx create --use
        docker buildx build --platform linux/arm64 --file Dockerfile.arm64 \
          $BUILD_ARGS \
          --load -t hpkv-image:${{ env.RELEASE_TAG }}-arm64 .
        docker save hpkv-image:${{ env.RELEASE_TAG }}-arm64 | gzip > hpkv-image-arm64.tar.gz
        docker buildx build --platform linux/amd64 --file Dockerfile.amd64 --load -t hpkv-image:${{ env.RELEASE_TAG }}-amd64 .
        docker save hpkv-image:${{ env.RELEASE_TAG }}-amd64 | gzip > hpkv-image-amd64.tar.gz
        docker cp $(docker create hpkv-image:${{ env.RELEASE_TAG }}-arm64):/app/kernel/hpkv_module_arm64.ko ./kernel/
        docker cp $(docker create hpkv-image:${{ env.RELEASE_TAG }}-amd64):/app/kernel/hpkv_module_x86_64.ko ./kernel/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-assets
        path: |
          ./kernel/hpkv_module_x86_64.ko
          ./kernel/hpkv_module_arm64.ko
          ./hpkv-image-amd64.tar.gz
          ./hpkv-image-arm64.tar.gz

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

  upload_assets:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - asset_name: hpkv_module_x86_64.ko
            asset_path: ./hpkv_module_x86_64.ko
            content_type: application/octet-stream
          - asset_name: hpkv_module_arm64.ko
            asset_path: ./hpkv_module_arm64.ko
            content_type: application/octet-stream
          - asset_name: hpkv-image-amd64.tar.gz
            asset_path: ./hpkv-image-amd64.tar.gz
            content_type: application/gzip
          - asset_name: hpkv-image-arm64.tar.gz
            asset_path: ./hpkv-image-arm64.tar.gz
            content_type: application/gzip

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-assets

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.build.outputs.upload_url }}
        asset_path: ${{ matrix.asset_path }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: ${{ matrix.content_type }}